export const FETCH_ALL_EMPLOYEE_SUCCESS = "FETCH_ALL_EMPLOYEE_SUCCESS";
export const FETCH_SINGLE_EMPLOYEE_SUCCESS ="FETCH_SINGLE_EMPLOYEE_SUCCESS";
export const FETCH_ALL_EMPLOYEE_ERROR = "FETCH_ALL_EMPLOYEE_ERROR";
export const FETCH_SINGLE_EMPLOYEE_ERROR ="FETCH_SINGLE_EMPLOYEE_ERROR"
export const FETCH_ALL_EMPLOYEE_POST_ERROR = "FETCH_ALL_EMPLOYEE_POST_ERROR";
export const FETCH_SINGLE_EMPLOYEE_POST_ERROR ="FETCH_SINGLE_EMPLOYEE_POST_ERROR"

